# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
# Site Settings
title: Private Email Discussion Groups | Group Mailing List Service 
email: your-email@example.com
description: Private Email Discussion Groups | Group Mailing List Service 
baseurl: "" # the subpath of your site, e.g. /blog
url: http://www.mail-list.com 
comments:
  provider               : # false (default), "disqus", "discourse", "facebook", "google-plus", "staticman", "custom"
  disqus:
    shortname            : # https://help.disqus.com/customer/portal/articles/466208-what-s-a-shortname-
  discourse:
    server               : # https://meta.discourse.org/t/embedding-discourse-comments-via-javascript/31963 , e.g.: meta.discourse.org
  facebook:
    # https://developers.facebook.com/docs/plugins/comments
    appid                :
    num_posts            : # 5 (default)
    colorscheme          : # "light" (default), "dark"
# SEO Related
google_site_verification :
bing_site_verification   :
alexa_site_verification  :
yandex_site_verification :
# Analytics
analytics:
  provider               : false # false (default), "google", "google-universal", "custom"
  google:
    tracking_id          :

# Social networks usernames. Shown in footer.
socials:
  - title: Facebook
    icon: fa-facebook
    url: https://www.facebook.com/ListServeCowboy  
  - title: LinkedIn
    icon: fa-linkedin
    url: https://www.linkedin.com/in/markdavidmccreary
  - title: Twitter
    icon: fa-twitter
    url: https://twitter.com/listservecowboy
  - title: Youtube
    icon: fa-youtube
    url: https://www.youtube.com/user/maillistcom



### Site Navigations
navigations: 
 - 
  title: "HOME"
  url: "index.html"
 - 
  title: "Services"
  url: ""
 - 
  title: "Compare"
  url: ""
 - 
  title: "Pricing"
  url: ""
 - 
  title: "About"
  url: ""
 - 
  title: "Contact Us"
  url: "contact.html"
 - 
  title: "Login"
  url: ""

### Footer Navigations  
footerNavigation: 
  legal:
    - 
      title: "Mail List Privacy"
      url: "/privacy/"
    - 
      title: "Security"
      url: "/security"
    - 
      title: "Terms of Service"
      url: "/terms-of-service/"
  about:
    - 
      title: "User Guide"
      url: "http://help.mail-list.com/m/59124"
    - 
      title: "FAQs"
      url: "/frequently-asked-questions/"
    - 
      title: "Videos"
      url: "/videos/"
    - 
      title: "News"
      url: "https://www.mail-list.com/news/"
# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style
  
# Build settings
markdown: kramdown
#theme: minima
gems:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
